# Generated by Django 4.0.3 on 2022-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='kind',
            new_name='Type',
        ),
    ]
